function imgRGB = interp_bicub(imgRGGB_d, RowI, RowP, ColI, ColP)
%% INTERPOLACIÓN BICÚBICA PARA PATRÓN BAYER RGGB
% Entrada:
%   imgRGGB_d - Imagen Bayer en formato double
%   RowI, RowP - Índices de filas impares y pares
%   ColI, ColP - Índices de columnas impares y pares
% Salida:
%   imgRGB - Imagen RGB interpolada (uint8)

[Rows, Cols] = size(imgRGGB_d);
imgRGB = zeros(Rows, Cols, 3, 'uint8');

% Coeficientes bicúbicos (4 puntos)
c1 = -1/16;  % Peso para I(u)
c2 = 9/16;   % Peso para I(u+2)
c3 = 9/16;   % Peso para I(u+4)
c4 = -1/16;  % Peso para I(u+6)

% 1. ASIGNAR PÍXELES ORIGINALES
imgRGB(RowI, ColI, 1) = imgRGGB_d(RowI, ColI);  % R
imgRGB(RowI, ColP, 2) = imgRGGB_d(RowI, ColP);  % G₁
imgRGB(RowP, ColI, 2) = imgRGGB_d(RowP, ColI);  % G₂
imgRGB(RowP, ColP, 3) = imgRGGB_d(RowP, ColP);  % B

% 2. INTERPOLACIÓN VERTICAL (ROJO)
% R en filas pares ≥ 4, columnas impares
k_rv = 4:2:Rows-4;
imgRGB(k_rv, ColI, 1) = uint8(...
    c1 * imgRGGB_d(k_rv-3, ColI) + ...
    c2 * imgRGGB_d(k_rv-1, ColI) + ...
    c3 * imgRGGB_d(k_rv+1, ColI) + ...
    c4 * imgRGGB_d(k_rv+3, ColI));

% 3. INTERPOLACIÓN HORIZONTAL (ROJO)
% R en todas las filas, columnas pares ≥ 4
l_rh = 4:2:Cols-4;
imgRGB(:, l_rh, 1) = uint8(...
    c1 * double(imgRGB(:, l_rh-3, 1)) + ...
    c2 * double(imgRGB(:, l_rh-1, 1)) + ...
    c3 * double(imgRGB(:, l_rh+1, 1)) + ...
    c4 * double(imgRGB(:, l_rh+3, 1)));

% 4. INTERPOLACIÓN VERTICAL (VERDE)
% Subred G₁: Verde en filas impares ≥ 5, columnas pares
k_g1 = 5:2:Rows-5;
imgRGB(k_g1, ColP, 2) = uint8(...
    c1 * imgRGGB_d(k_g1-3, ColP) + ...
    c2 * imgRGGB_d(k_g1-1, ColP) + ...
    c3 * imgRGGB_d(k_g1+1, ColP) + ...
    c4 * imgRGGB_d(k_g1+3, ColP));

% Subred G₂: Verde en filas pares ≥ 4, columnas impares
k_g2 = 4:2:Rows-4;
imgRGB(k_g2, ColI, 2) = uint8(...
    c1 * imgRGGB_d(k_g2-3, ColI) + ...
    c2 * imgRGGB_d(k_g2-1, ColI) + ...
    c3 * imgRGGB_d(k_g2+1, ColI) + ...
    c4 * imgRGGB_d(k_g2+3, ColI));

% 5. INTERPOLACIÓN VERTICAL (AZUL)
% B en filas impares ≥ 5, columnas pares
k_bv = 5:2:Rows-5;
imgRGB(k_bv, ColP, 3) = uint8(...
    c1 * imgRGGB_d(k_bv-3, ColP) + ...
    c2 * imgRGGB_d(k_bv-1, ColP) + ...
    c3 * imgRGGB_d(k_bv+1, ColP) + ...
    c4 * imgRGGB_d(k_bv+3, ColP));

% 6. INTERPOLACIÓN HORIZONTAL (AZUL)
% B en todas las filas, columnas impares ≥ 5
l_bh = 5:2:Cols-5;
imgRGB(:, l_bh, 3) = uint8(...
    c1 * double(imgRGB(:, l_bh-3, 3)) + ...
    c2 * double(imgRGB(:, l_bh-1, 3)) + ...
    c3 * double(imgRGB(:, l_bh+1, 3)) + ...
    c4 * double(imgRGB(:, l_bh+3, 3)));

end